### ISSUE TITLE
Let add transition act like set transition the first time I use it

### ISSUE THREAD

**Issue by lukovdm** [moves-rwth/stormvogel#103]
When I am dynamically adding transitions to a state, I now have to add logic to choose `set_transition` the first time I want to add a transition and `add_transition` the second time I want to add a transition. So my proposal is to let `add_transition` act like `set_transition` when no transition has been set yet.

**Comment by linusheck** [comment]
Sounds good :)

**Comment by YouGuessedMyName** [comment]
Should now be live on main :)
