### ISSUE TITLE
Testing framework

### ISSUE THREAD

**Issue by YouGuessedMyName** [moves-rwth/stormvogel#3]
Right now, testing is just done using functions with assert statements. This is quite unusual for a Python project. I suggest we switch to the unittest framework.

**Comment by linusheck** [comment]
We're currently using the pytest framework, which indeed just uses functions and assertions. I personally prefer pytest over unittest. [Here's](https://blog.jetbrains.com/pycharm/2024/03/pytest-vs-unittest/) a comprehensive comparison

**Comment by YouGuessedMyName** [comment]
Then let's stick to that
