### ISSUE TITLE
Model builder API

### ISSUE THREAD

**Issue by PimLeerkes** [moves-rwth/stormvogel#4]
create a flexible and easy to use model builder API

**Comment by YouGuessedMyName** [comment]
If I understand correctly, the model builder API is the existing API in storm right? So the task is to convert between the new API that linus made and that?

**Comment by linusheck** [comment]
I think the conversion issue is this one: https://github.com/moves-rwth/stormvogel/issues/6

This is about improving the existing https://github.com/moves-rwth/stormvogel/blob/main/stormvogel/model.py
