### ISSUE TITLE
Simpler MDP example.

### ISSUE THREAD

**Issue by YouGuessedMyName** [moves-rwth/stormvogel#8]
Monty hall seems quite complicated. For new users, it is probably easier to look at a very simple MDP model first.

**Comment by volkm** [comment]
One possible example could be the music shuffle example from [this tutorial](https://github.com/moves-rwth/stormpyter/blob/master/tutorial_discotec2020/discotec_stormpy.ipynb).

**Comment by YouGuessedMyName** [comment]
I just added a very rudimentary example called study.inpb. In the future we can also add the example you linked to :).
