### ISSUE TITLE
Multiple visualisations in one notebook don't work

### ISSUE THREAD

**Issue by lukovdm** [moves-rwth/stormvogel#95]
When I have multiple visualisations (calling `show` on models) in one notebook. Even when they are from separate code blocks. The last call to `show` is shown in all visualisations.

I think somehow `show` is written to all frames containing a stormvogel visualisation.

**Comment by YouGuessedMyName** [comment]
Interesting, I will try to solve it soon.

**Comment by YouGuessedMyName** [comment]
Could you send me some code that produces this bug?

**Comment by YouGuessedMyName** [comment]
Nevermind, it should be fixed now. Thanks for letting us know :)
